#!/usr/bin/env bash
# prints all the numbers to 100
# but multiples of 3 fizz and 5 buzz
# both fizzbuzz

for i in {1..100}
do
if (( $i % 3 == 0 && $i % 5 == 0 ))
then
echo "FizzBuzz"
elif (( $i % 5 == 0 ))
then
echo "Buzz"
elif (( $i % 3 == 0 ))
then
echo "Fizz"
else
echo "$i"
fi
done