#!/usr/bin/env bash
# prints all the numbers to 100
# but multiples of 3 fizz and 5 buzz
# both fizzbuzz

i=1

while [ $i -lt 101 ]
do
if (($i % 3 == 0 && $i % 5 == 0))
then
echo "FizzBuzz"
elif (($i % 5 == 0))
then
echo "Buzz"
elif (($i % 3 == 0))
then
echo "Fizz"
else
echo "$i"
fi
((i++))
done