#!/usr/bin/env bash
# prints first 20 number

for i in {1..20}
do
echo "$i"
if [ $i -eq 4 ]
then
echo "bad luck from China"
fi
if [ $i -eq 9 ]
then
echo "bad luck from Japan"
fi
if [ $i -eq 17 ]
then
echo "bad luck from Italy"
fi
done